#cloud-config
runcmd:
  - curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl
  - chmod +x /usr/local/bin/kubectl
  - git clone --recurse-submodules -j4 https://github.com/rackerlabs/genestack /opt/genestack
package_update: true
