---
- name: Label storage nodes
  hosts: ceph_storage_nodes
  tags: label_nodes
  roles:
    - role: rackspace.genestack.label_nodes
      vars:
        label_dictionary:
          role: "storage-node"
  tasks: []

- name: Label control plane nodes
  hosts: openstack_control_plane
  tags: label_nodes
  roles:
    - role: rackspace.genestack.label_nodes
      vars:
        label_dictionary:
          openstack-control-plane: enabled
  tasks: []

- name: Label nova compute nodes
  hosts: nova_compute_nodes
  tags: label_nodes
  roles:
    - role: rackspace.genestack.label_nodes
      vars:
        label_dictionary:
          openstack-compute-node: enabled
  tasks: []

- name: Label openstack network nodes
  hosts: ovn_network_nodes:nova_compute_nodes
  tags: label_nodes
  roles:
    - role: rackspace.genestack.label_nodes
      vars:
        label_dictionary:
          openstack-network-node: enabled
  tasks: []

- name: Label worker nodes
  hosts: openstack_control_plane:openstack_worker_nodes
  tags: label_nodes
  roles:
    - role: rackspace.genestack.label_nodes
      vars:
        label_dictionary:
          node-role.kubernetes.io/worker: worker
  tasks: []

- name: Remove taint from controllers
  hosts: kube_control_plane
  tags: taint_nodes
  tasks:
    - name: Remove taint
      kubernetes.core.k8s_taint:
        state: absent
        name: "{{ inventory_hostname }}"
        taints:
          - effect: NoSchedule
      delegate_to: localhost

- name: Deploy k8s dashboard
  hosts: localhost
  connection: local
  tags: deploy_dashboard
  tasks:
    - name: Deploy k8s dashboard
      kubernetes.core.k8s:
        definition: "{{ lookup('kubernetes.core.kustomize', dir='/opt/genestack/base-kustomize/k8s-dashboard') }}"
        apply: true

- name: Deploy prometheus
  hosts: localhost
  connection: local
  tags: deploy_prometheus
  tasks:
    # Not happy about this but deploying prometheus fails on the first run.
    # TODO: Find a way to do this cleanly using the kubernetes.core.k8s module
    - name: Deploy prometheus # noqa: no-changed-when risky-shell-pipe
      ansible.builtin.shell:
        cmd: kubectl kustomize --enable-helm /opt/genestack/base-kustomize/prometheus | kubectl apply --server-side -f -
      retries: 2
      delay: 2
      register: deploy_prometheus_result
      until: deploy_prometheus_result is not failed

- name: Make helm charts
  hosts: localhost
  connection: local
  tags: make_helm_charts
  tasks:
    - name: Make helm charts
      community.general.make:
        chdir: "{{ item }}"
        target: all
      loop:
        - /opt/genestack/submodules/openstack-helm
        - /opt/genestack/submodules/openstack-helm-infra

## Ceph internal section
## https://docs.rackspacecloud.com/storage-ceph-rook-internal/
- name: Ceph internal
  hosts: localhost
  connection: local
  tags: ceph_internal
  roles:
    - rackspace.genestack.ceph_internal
  tasks: []

# ### Infrastructre section
# ### https://docs.rackspacecloud.com/infrastructure-overview/

- name: OpenStack namespace
  hosts: localhost
  connection: local
  tags: openstack_namespace
  tasks:
    - name: Create OpenStack namespace
      kubernetes.core.k8s:
        name: openstack
        api_version: v1
        kind: Namespace
        state: present

# ### https://docs.rackspacecloud.com/infrastructure-gateway-api/

- name: GatewayAPI
  hosts: localhost
  connection: local
  tags: gatewayapi
  roles:
    - rackspace.genestack.galaxyapi
  tasks: []

# ### https://docs.rackspacecloud.com/infrastructure-letsencrypt/
- name: LetsEncrypt
  hosts: localhost
  connection: local
  tags: letsencrypt
  vars_prompt:
    - name: letsencrypt_email
      prompt: Email for letsencrypt?
      private: false
  roles:
    - rackspace.genestack.letsencrypt
  tasks: []

# ### https://docs.rackspacecloud.com/infrastructure-mariadb/
- name: MariaDB
  hosts: localhost
  connection: local
  tags: mariadb
  vars:
    secret_name: mariadb
    cluster_name: cluster.local
  roles:
    - role: rackspace.genestack.mariadb
      vars:
        secret_name: mariadb
        cluster_name: cluster.local
  tasks: []

### https://docs.rackspacecloud.com/infrastructure-rabbitmq/#deploy-the-rabbitmq-operator
- name: RabbitMQ
  hosts: localhost
  connection: local
  tags: rabbitmq
  roles:
    - rackspace.genestack.rabbitmq
  tasks: []

### https://docs.rackspacecloud.com/infrastructure-memcached/#deploy-the-memcached-cluster
- name: Memcached
  hosts: localhost
  connection: local
  tags: memcached
  roles:
    - rackspace.genestack.memcached
  tasks: []

### https://docs.rackspacecloud.com/infrastructure-libvirt/
- name: Libvirt
  hosts: localhost
  connection: local
  tags: libvirt
  roles:
    - rackspace.genestack.libvirt
  tasks: []

### The ovn and ovn_annotate roles are tightly coupled.  The reason for seperate
### roles is that the annotation is added for the network and compute nodes and
### the ovn role is performed from localhost.
### https://docs.rackspacecloud.com/infrastructure-ovn-setup/
- name: Annotate network enabled nodes
  hosts: ovn_network_nodes:nova_compute_nodes
  tags: ovn
  roles:
    - rackspace.genestack.ovn_annotate
  tasks: []

### https://docs.rackspacecloud.com/infrastructure-ovn-setup/#run-the-ovn-integration
- name: Apply OVN integration
  hosts: localhost
  tags: ovn
  roles:
    - rackspace.genestack.ovn
  tasks: []

- name: MetalLB config
  hosts: localhost
  tags: metallb
  roles:
    - rackspace.genestack.metallb
  tasks: []
